image: gitpod/workspace-full

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - Pivotal.vscode-boot-dev-pack
    - redhat.vscode-xml
    - pivotal.vscode-spring-boot
    - vscjava.vscode-java-pack
    - GabrielBB.vscode-lombok
    - bajdzis.vscode-database
    - vivaxy.vscode-conventional-commits

tasks:
  - name: Prepare env
    init: |
      yes | sdk install java 21.0.6-tem && cd /workspace/QLACK-Base-Application/qlack-base-application-server && mvn clean install
      cd /workspace/QLACK-Base-Application/qlack-base-application-ui && npm install && npx -y @angular/cli build
    command: gp sync-done env
  - name: Backend
    before: |
      sdk install java 21.0.6-tem < /dev/null
      sdk use java 21.0.6-tem
    command: |
      gp sync-await env
      sdk use java 21.0.6-tem
      export JAVA_HOME=$(sdk home java 21.0.6-tem)
      export PATH=$JAVA_HOME/bin:$PATH
      cd /workspace/QLACK-Base-Application/qlack-base-application-server
      mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -XX:+ShowCodeDetailsInExceptionMessages -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8081" -Dspring-boot.run.arguments="--server.port=8080"
  - name: Frontend
    command: |
      gp sync-await env
      cd /workspace/QLACK-Base-Application/qlack-base-application-ui
      npx -y @angular/cli serve --host 0.0.0.0 --disable-host-check --proxy-config proxy.conf.json

ports:
  - port: 4200
    visibility: private
    onOpen: open-preview
